name: Comment Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commands: test-deploy
          reactions: false