name: Deploy Test Container
on:
  repository_dispatch:
    types: [test-deploy-command]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add start reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
      - name: Checkout the branch to test
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          ref: ${{ github.event.client_payload.pull_request.head_ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Docker TEST image
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: mvn --batch-mode package dockerfile:push@test-env
      - name: Add success reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray