name: Push Image and update latest ver.
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
  build_push_job:
    runs-on: ubuntu-latest
    name: Push docker image
    needs: build
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
